name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v0.13.2
      
      # We're picking a specific test case to run against.
      - run: terraform init
        working-directory: test/aws/terraform/ec2_role_share_rule/public_and_private_ec2_same_role
      - run: terraform plan -out=plan.out
        working-directory: test/aws/terraform/ec2_role_share_rule/public_and_private_ec2_same_role
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Confirm we have the plan file
      - run: stat plan.out
        working-directory: test/aws/terraform/ec2_role_share_rule/public_and_private_ec2_same_role
          
      - uses: indeni/cloudrail-run-ga@v0.7
        with:
          tf-plan-file: plan.out
          cloudrail-api-key: ${{ secrets.CLOUDRAIL_API_KEY }}
          cloud-account-id: 473085186055
          working-directory: test/aws/terraform/ec2_role_share_rule/public_and_private_ec2_same_role # Note, this is not part of the GitHub action syntax, but a parameter of the action
